version: '3.4'
x-server-environment: &server-environment
    DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@postgres:5432/postgres}
    REDIS_URL: ${REDIS_URL:-redis://redis:6379}
    REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET:-redash_cookie_secret}

x-server-image: &server-image
    build:
        context: .
        dockerfile: docker/Dockerfile
    environment:
        <<: *server-environment

services:
    server:
        <<: *server-image
        ports:
            - 3000:3000
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            <<: *server-environment
            PORT: ${PORT:-3000}
        depends_on:
            - redis
            - worker
            - scheduler

    worker:
        <<: *server-image
        build:
          dockerfile: Dockerfile.worker
        depends_on:
            - redis
            - postgres

    scheduler:
        <<: *server-image
        build:
          dockerfile: Dockerfile.scheduler


    redis:
        image: redis
        command: redis-server --appendonly yes
        volumes:
            - ./.docker-volumes/redis:/data
        expose:
            - 6379

    postgres:
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_DB: ${POSTGRES_DB:-postgres}
        volumes:
            - ./.docker-volumes/postgres:/var/lib/postgresql/data
        expose:
            - 5432